name: azure_pipeline.yml

on:
  push:
    branches:
      - main
      
jobs:
  postman-test-api:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v2
      
    # Install Node on the runner
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    # Install project dependencies
    - name: Install Dependencies
      run: npm install

    # Start the Node.js application in the background
    - name: Start Node.js Application
      run: |
        nohup npm start &
    
    # Wait for the application to be fully up and running
    - name: Wait for Application to Start
      run: |
        while ! curl -s http://localhost:3006/ > /dev/null; do
          echo "Waiting for application to start..."
          sleep 2
        done
    
    # Install the newman command line utility
    - name: Install newman
      run: npm install -g newman

    # Run the Postman collection to console
    - name: Run POSTMAN collection to console
      run: newman run ./Movie-shop.postman_collection.json -e Production.postman_environment.json

    # Upload the contents of Test Results directory to workspace
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
        name: RunReports
        path: testResults
